# Generated by Django 5.2.7 on 2025-10-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_api', '0002_alter_country_estimated_gdp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='last_refreshed_at',
        ),
    ]
